add_newline = false
format = " [─](dimmed black) $time$hostname$cmd_duration$fill $directory$git_branch$git_state[─](dimmed black)\n$character"

[fill]
symbol = "─"
style = "dimmed black"

[hostname]
style = "yellow"
format = "[─](dimmed black) [$hostname]($style) "

[directory]
truncation_length = 10
style = "bold black"

[git_branch]
style = "yellow"
format = "[$symbol$branch(:$remote_branch)]($style) "

[character]
success_symbol = "[象](bold yellow)"
error_symbol = "[死](bold red)"
vicmd_symbol = "[象](bold green)"

[golang]
format = "[$version](bold cyan) "
disabled = true

[time]
disabled = false
style = "bold black"
format = "[$time]($style) "

[cmd_duration]
min_time = 100
show_milliseconds = true
format = "[─](dimmed black) [$duration]($style) "
style = "bold cyan"
