add_newline = false
format = "$time$hostname$cmd_duration$fill $directory$git_branch$git_state\n$character"

[fill]
symbol = "â”€"
style = "dimmed black"

[hostname]
style = "yellow"
format = "[â”](dimmed black) [$hostname]($style) "

[directory]
truncation_length = 10
style = "bold black"

[git_branch]
style = "yellow"
format = "[$symbol$branch(:$remote_branch)]($style) "

[character]
success_symbol = "[ğŸ¡ª](bold purple) "
error_symbol = "[ğŸ¡ª](bold red) "
vicmd_symbol = "[â®](bold green)"

[golang]
format = "[$version](bold cyan) "
disabled = true

[time]
disabled = false
style = "bold black"
format = "[$time]($style) "

[cmd_duration]
min_time = 100
show_milliseconds = true
format = "[â”€](dimmed black) [$duration]($style) "
style = "bold cyan"
